#!/usr/bin/env python3
"""Tolkyn PBX -> multi-tenant sync.

Pulls the current DID / SIP-extension / workspace assignments from the
backend (super admin's Telephony page writes these) and makes the live
Asterisk config match: one PJSIP endpoint + one voicemail mailbox per agent
extension, and an AstDB routing table so the dialplan can turn "a call came
in for DID X" into "ring extension Y" without ever hardcoding a client.

Run periodically by a systemd timer (tolkyn-sync-workspaces.timer) — this
script is idempotent and safe to run as often as you like: it only rewrites
a file / touches AstDB / reloads Asterisk when something actually changed.

Config comes from the repo-root .env, same file the AMI bridge and
voicemail-notify.sh already read (asterisk/install-on-host.sh writes it):

    PBX_EVENT_BACKEND_URL=http://127.0.0.1:8090/api/v1
    PBX_EVENT_WEBHOOK_SECRET=...

Pure standard library — no pip installs on the host.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List

CONF_ENV = Path("/etc/tolkyn/ami-bridge.env")
PJSIP_FILE = Path("/etc/asterisk/pjsip_workspaces.conf")
VOICEMAIL_FILE = Path("/etc/asterisk/voicemail_workspaces.conf")
ASTDB_FAMILY = "tolkyn"


def log(*a: object) -> None:
    print(time.strftime("%Y-%m-%d %H:%M:%S"), *a, flush=True)


def load_env() -> Dict[str, str]:
    if not CONF_ENV.exists():
        log(f"{CONF_ENV} not found — has install-on-host.sh been run?")
        sys.exit(1)
    env: Dict[str, str] = {}
    for line in CONF_ENV.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        env[k.strip()] = v.strip()
    return env


def fetch_routing(backend: str, secret: str) -> List[Dict[str, str]]:
    url = f"{backend.rstrip('/')}/call-center/pbx-routing"
    req = urllib.request.Request(url, headers={"X-Webhook-Secret": secret})
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read())
    return data.get("lines", [])


def last9(number: str) -> str:
    digits = re.sub(r"\D", "", number or "")
    return digits[-9:] if len(digits) >= 9 else digits


# --- generated config files -------------------------------------------------
def render_pjsip(lines: List[Dict[str, str]]) -> str:
    parts = [
        "; Generated by asterisk/sync_workspaces.py — DO NOT HAND-EDIT.",
        "; Regenerated on every sync run from telephony_configs + call_agents.",
        "",
    ]
    for ln in sorted(lines, key=lambda x: x["extension"]):
        ext = ln["extension"]
        parts.append(f"[{ext}_auth]")
        parts.append("type = auth")
        parts.append("auth_type = userpass")
        parts.append(f"username = {ext}")
        parts.append(f"password = {ln['password']}")
        parts.append("")
        parts.append(f"[{ext}]")
        parts.append("type = aor")
        parts.append("max_contacts = 3")
        parts.append("remove_existing = yes")
        parts.append("")
        parts.append(f"[{ext}]")
        parts.append("type = endpoint")
        parts.append("transport = transport-ws")
        parts.append("context = from-internal")
        parts.append("disallow = all")
        # G.711 only — the base Asterisk package has no Opus codec, so an
        # Opus browser leg can't be transcoded to the G.711 trunk.
        parts.append("allow = ulaw")
        parts.append("allow = alaw")
        parts.append(f"auth = {ext}_auth")
        parts.append(f"aors = {ext}")
        parts.append("webrtc = yes")
        parts.append("dtls_auto_generate_cert = yes")
        parts.append(f"mailboxes = {ext}@default")
        parts.append(f"callerid = {ext}")
        parts.append("direct_media = no")
        # Consumed by extensions.conf.template's [from-internal] / *97 — makes
        # every call this endpoint places carry its own workspace's DID as
        # caller ID, and its own mailbox for voicemail retrieval, with zero
        # per-workspace dialplan logic.
        parts.append(f"set_var = DID={ln['did']}")
        parts.append(f"set_var = MYEXT={ext}")
        parts.append("")
    return "\n".join(parts) + "\n"


def render_voicemail(lines: List[Dict[str, str]]) -> str:
    parts = [
        "; Generated by asterisk/sync_workspaces.py — DO NOT HAND-EDIT.",
    ]
    for ln in sorted(lines, key=lambda x: x["extension"]):
        parts.append(f"{ln['extension']} => 0000,Agent,,,attach=no")
    return "\n".join(parts) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def asterisk_rx(cmd: str) -> str:
    try:
        r = subprocess.run(
            ["asterisk", "-rx", cmd], capture_output=True, text=True, timeout=10
        )
        return r.stdout
    except Exception as e:  # noqa: BLE001
        log(f"asterisk -rx {cmd!r} failed: {e}")
        return ""


# --- AstDB routing table ----------------------------------------------------
def astdb_current() -> Dict[str, str]:
    out = asterisk_rx(f"database show {ASTDB_FAMILY}")
    current: Dict[str, str] = {}
    for line in out.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip().lstrip("/")
        if not key.startswith(f"{ASTDB_FAMILY}/"):
            continue
        current[key[len(ASTDB_FAMILY) + 1:]] = val.strip()
    return current


def astdb_sync(lines: List[Dict[str, str]]) -> None:
    desired: Dict[str, str] = {}
    for ln in lines:
        did9 = last9(ln["did"])
        if not did9:
            continue
        desired[f"did/{did9}"] = ln["extension"]
        desired[f"ext_did/{ln['extension']}"] = ln["did"]
        desired[f"ext_ws/{ln['extension']}"] = ln["workspace_id"]
        desired[f"ext_record/{ln['extension']}"] = "1" if ln.get("record_calls") else "0"

    current = astdb_current()
    changed = 0
    for key, val in desired.items():
        if current.get(key) != val:
            asterisk_rx(f"database put {ASTDB_FAMILY} {key} {val}")
            changed += 1
    for key in current:
        if key not in desired:
            asterisk_rx(f"database del {ASTDB_FAMILY} {key}")
            changed += 1
    if changed:
        log(f"AstDB: {changed} entr{'y' if changed == 1 else 'ies'} updated")


def main() -> int:
    env = load_env()
    backend = env.get("PBX_EVENT_BACKEND_URL", "http://127.0.0.1:8090/api/v1")
    secret = env.get("PBX_EVENT_WEBHOOK_SECRET", "")
    if not secret:
        log("PBX_EVENT_WEBHOOK_SECRET not set — exiting")
        return 1

    try:
        lines = fetch_routing(backend, secret)
    except urllib.error.HTTPError as e:
        log("routing fetch HTTP error:", e.code, e.read()[:200])
        return 1
    except Exception as e:  # noqa: BLE001
        log("routing fetch failed:", e)
        return 1

    # Every line needs a DID, an extension and a password — the backend
    # already filters to that, but never trust a wire payload blindly.
    lines = [ln for ln in lines if ln.get("did") and ln.get("extension") and ln.get("password")]
    exts = [ln["extension"] for ln in lines]
    if len(exts) != len(set(exts)):
        log("routing table has a duplicate extension — refusing to write a broken config")
        return 1

    # A routing table that comes back EMPTY while a real (non-header-only)
    # config is already live almost never means "remove every agent" — far
    # more likely a transient backend hiccup. Never let that silently drop
    # every currently-registered line; leave the live config alone and log
    # loudly instead. An empty table on a genuinely first run (no file yet)
    # is fine — there's nothing live to break.
    if not lines and PJSIP_FILE.exists() and len(PJSIP_FILE.read_text().splitlines()) > 3:
        log("routing table came back empty but a live config already exists — "
            "leaving it untouched (not deprovisioning every agent on a hiccup)")
        return 1

    pjsip_changed = write_if_changed(PJSIP_FILE, render_pjsip(lines))
    vm_changed = write_if_changed(VOICEMAIL_FILE, render_voicemail(lines))

    astdb_sync(lines)

    if pjsip_changed:
        log(f"pjsip_workspaces.conf changed ({len(lines)} line(s)) — reloading pjsip")
        asterisk_rx("pjsip reload")
    if vm_changed:
        log("voicemail_workspaces.conf changed — reloading voicemail")
        asterisk_rx("module reload app_voicemail.so")

    if not (pjsip_changed or vm_changed):
        log(f"no changes ({len(lines)} line(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
