"""add_leads_table

Revision ID: e56746a46947
Revises: 
Create Date: 2026-09-01 21:01:11.373899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56746a46947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('LINKEDIN', 'INSTAGRAM', 'FACEBOOK', 'TWITTER', 'WEBSITE', 'EMAIL', 'REFERRAL', 'MANUAL', 'SCRAPED', name='leadsource'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', 'UNQUALIFIED', name='leadstatus'), nullable=False),
    sa.Column('score', sa.Enum('HOT', 'WARM', 'COLD', 'UNKNOWN', name='leadscore'), nullable=False),
    sa.Column('engagement_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INACTIVE', name='leadengagementlevel'), nullable=False),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('ai_intent_signals', sa.JSON(), nullable=True),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('decision_maker', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('scraped_from', sa.String(length=255), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_company'), 'leads', ['company'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_index('ix_leads_workspace_created', 'leads', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_index('ix_leads_workspace_score', 'leads', ['workspace_id', 'score'], unique=False)
    op.create_index('ix_leads_workspace_status', 'leads', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_workspace_status', table_name='leads')
    op.drop_index('ix_leads_workspace_score', table_name='leads')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index('ix_leads_workspace_created', table_name='leads')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
